
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "azure"
  config.vm.box_url = 'https://github.com/msopentech/vagrant-azure/raw/master/dummy.box'

  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.define "localhost" do |l|
          l.vm.hostname = "localhost"
  end


  config.vm.provider :azure do |azure, override|
    azure.mgmt_certificate = '/home/angel/Prueba/azurevagrant.pem'
    azure.mgmt_endpoint = 'https://management.core.windows.net'
    azure.subscription_id = '8afb40f4-4482-4a5c-832a-b7aab655fed1'
    azure.vm_image = 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2-LTS-amd64-server-20150506-en-us-30GB'
    azure.vm_name = 'maquinaavm'
    azure.vm_password = 'Clave#Angel#1'
    azure.vm_location = 'Central US'
        azure.ssh_port = '22'
        azure.tcp_endpoints = '80:80'
  end


  config.vm.provision "ansible" do |ansible|
        ansible.sudo = true
        ansible.playbook = "playbookIV.yml"
        ansible.verbose = "v"
  end
end
